import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { motion as m } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-96 p-1">
          <h1 className="text-6xl text-center lg:text-right lg:text-9xl">
            Happy Birthday
          </h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h3>It's</h3>
            <h3>Your</h3>
            <h3>Big Day</h3>
          </div>
          <div>
            <h3>It's only about your happy day.</h3>
            <h3>Full of colors in your life</h3>
            <h3>Scroll more for hidden secrets</h3>
            
          </div>
        </div>
      </main>
    </>
  );
}
